---
- name: Provision 3 Tier OSP Install 
  hosts: jumpbox
#  become: yes
  roles:
    - osp-network
    - osp-keypair
    - osp-securitygroup
    - osp-flavor
  tasks:
    ## Alternate Method to create dynmaic inventory
    - name: Gather facts
      include_role: 
        name: osp-facts
      tags:
      - test_inventory
##Create Fronend Instance
    - name: Create frontend instance
      include_role:
        name: osp-instance-delete
        vars_from: frontend.yaml
  ###Create App1 server 
    - name: Create app1 instance
      include_role:
        name: osp-instance-delete
        vars_from: app1.yaml
  ##Create App2 server
    - name: Create app2 instance
      include_role:
        name: osp-instance-delete
        vars_from: app2.yaml
  ##Create DB server
    - name: Create db instance
      include_role:
        name: osp-instance-delete
        vars_from: db.yaml
  # ## Alternate Method to create dynmaic inventory
  #   - name: Gather facts
  #     include_role: 
  #       name: osp-facts
  #     tags:
  #     - test_inventory
  #   - name: Fetch Instance Info
  #     os_server_facts:
  #       cloud: ospcloud
  #       region_name: RegionOne
  #     register: result
  #   - name: Start servers 
  #     os_server_actions:
  #       action: start
  #       server: "{{ item.name }}"
  #     with_items: "{{result.ansible_facts.openstack_servers}}"
