---

# Playbook utilized from course material.
# https://www.opentlc.com/labs/tmp/ansible_advanced/05_Cloud_Infrastructure/05_Cloud_Infrastructure_Solution_Lab.html
# Playbooks located at bottom of course material:
# - https://github.com/prakhar1985/good-ansible/blob/master/3tier-good/

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier
# `ansible-galaxy install geerlingguy.postgresql -p ./roles` to get this installed into your projects relative directory.
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}

# Smoke test the application
- name: check tomcat serving via haproxy
  uri:
    url: http://frontend1.9ce4.example.opentlc.com/ansible