---
- name: Configure 3 Tier OSP Install 
  hosts: jumpbox
#  become: yes
  roles:
    - osp-network
    - osp-keypair
    - osp-securitygroup
    - osp-flavor
  tasks:
##Create Fronend Instance
    - name: Create frontend instance
      include_role:
        name: osp-instances
        vars_from: frontend.yaml
  ###Create App1 server 
    - name: Create app1 instance
      include_role:
        name: osp-instances
        vars_from: app1.yaml
  ##Create App2 server
    - name: Create app2 instance
      include_role:
        name: osp-instances
        vars_from: app2.yaml
  ##Create DB server
    - name: Create db instance
      include_role:
        name: osp-instances
        vars_from: db.yaml
  ## Alternate Method to create dynmaic inventory
    - name: Gather facts
      include_role: 
        name: osp-facts
      tags:
      - test_inventory
    - name: Fetch Instance Info
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result
    - name: Start servers 
      os_server_action:
        action: start
        server: "{{ item.name }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier
# `ansible-galaxy install geerlingguy.postgresql -p ./roles` to get this installed into your projects relative directory.
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}
