---
- name: Configure 3 Tier OSP Install 
  hosts: jumpbox
  tasks:
  ## Alternate Method to create dynmaic inventory
    - name: Gather facts
      include_role: 
        name: osp-facts

# Setup front-end load balancer tier
- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier
# `ansible-galaxy install geerlingguy.postgresql -p ./roles` to get this installed into your projects relative directory.
- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}